# Generated by Django 5.2.4 on 2025-07-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="firebase_uid",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
