# Generated by Django 5.1.4 on 2025-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_post_is_apparel_appareltag"),
    ]

    operations = [
        migrations.AddField(
            model_name="appareltag",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="appareltag",
            name="pattern",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="appareltag",
            name="style",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
