# Generated by Django 5.1.4 on 2025-07-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_appareltag_color_appareltag_pattern_appareltag_style"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appareltag",
            old_name="pattern",
            new_name="item",
        ),
        migrations.RemoveField(
            model_name="appareltag",
            name="style",
        ),
    ]
